# syntax=docker/dockerfile:1

FROM nvidia/cuda:12.9.0-cudnn-runtime-ubuntu22.04

ENV TZ=Europe/Kyiv
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_NO_CACHE_DIR=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common ca-certificates curl wget git gnupg nano less \
       build-essential pkg-config \
       libffi-dev libssl-dev zlib1g-dev xz-utils liblzma-dev libbz2-dev libreadline-dev libncursesw5-dev uuid-dev libgdbm-dev \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends python3.13 python3.13-venv python3-setuptools \
       libssl3 libffi8 zlib1g xz-utils liblzma5 libbz2-1.0 libreadline8 libncursesw6 libgdbm6 libuuid1 tk

RUN ln -s /usr/bin/python3.13 /usr/local/bin/python \
    && ln -s /usr/bin/python3.13 /usr/local/bin/py

RUN py -m ensurepip --upgrade && py -m pip install --upgrade pip

RUN py -m pip install --index-url https://download.pytorch.org/whl/cu129 torch
RUN py -m pip install transformers
RUN py -m pip install pydantic fastapi[standard] python-dotenv rich openai accelerate bitsandbytes==0.47.* sentencepiece==0.2.* protobuf==6.32.*

RUN git clone --depth=1 --branch main https://github.com/WitalijKaa/special-creativity-ai /var/www/html/ai
WORKDIR /var/www/html/ai
RUN py -m pip install -r requirements.txt

RUN apt-get purge -y --auto-remove build-essential pkg-config python3.13-venv python3-setuptools && rm -rf /var/lib/apt/lists/*
