# syntax=docker/dockerfile:1

FROM pytorch/pytorch:2.8.0-cuda12.9-cudnn9-runtime

ENV TZ=Europe/Kyiv
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_NO_CACHE_DIR=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl wget git nano less \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install transformers
RUN python3 -m pip install pydantic fastapi[standard] python-dotenv rich openai accelerate bitsandbytes==0.47.* sentencepiece==0.2.* protobuf==6.32.*

RUN git clone --depth=1 --branch d.0002 https://github.com/WitalijKaa/special-creativity-ai /var/www/html/ai
WORKDIR /var/www/html/ai

RUN rm -rf /root/.cache/pip
