services:
  php:
    image: special-creativity
    container_name: sc_php
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8042:80"
      - "8043:443"
    volumes:
      #- php_dir:/var/www/html/sc
      - python_dir:/var/www/html/ai
      - hugging_face_cache:/hugging_face_cache
    depends_on:
      php_database:
        condition: service_healthy
      php_cache:
          condition: service_healthy
    command:
      sh -c "php artisan migrate --force && apache2-foreground"
    environment:
      HF_HOME: /hugging_face_cache

  php_database:
    image: mysql:8.4.4
    container_name: sc_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: php_creativity
      MYSQL_USER: basic
      MYSQL_PASSWORD: basic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - php_database_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 22s
      timeout: 11s
      retries: 7
      start_period: 80s

  php_cache:
    image: redis:7-alpine
    container_name: sc_redis
    restart: unless-stopped
    ports:
      - "63790:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - php_cache_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 22s
      timeout: 11s
      retries: 7
      start_period: 42s

volumes:
  php_database_volume:
  php_cache_volume:
  php_dir:
  python_dir:
  hugging_face_cache:
